// <auto-generated />
namespace MVCTreeview.Migrations.EmployeeMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PassData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PassData));
        
        string IMigrationMetadata.Id
        {
            get { return "201808261951324_PassData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
